// FUG OS actions
export const LOAD_APP = 'LOAD_APP';
export const GET_IMAGE_COLLECTION = 'GET_IMAGE_COLLECTION';
export const REQUEST_IMAGE_COLLECTION = 'REQUEST_IMAGE_COLLECTION';
export const RECEIVE_IMAGE_COLLECTION = 'RECEIVE_IMAGE_COLLECTION';
